// <auto-generated />
namespace WarehouseSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class warehouseitemmeasureunitcreating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(warehouseitemmeasureunitcreating));
        
        string IMigrationMetadata.Id
        {
            get { return "202203172139335_warehouse-item-measureunit-creating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
