// <auto-generated />
namespace WarehouseSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class customersupplierCreating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customersupplierCreating));
        
        string IMigrationMetadata.Id
        {
            get { return "202203172221458_customer-supplier-Creating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
