// <auto-generated />
namespace WarehouseSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class creatingwarehouseitementity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creatingwarehouseitementity));
        
        string IMigrationMetadata.Id
        {
            get { return "202203222350393_creating-warehouseitem-entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
